In [1]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=5)

### we can use loadtxt or genfromtxt which takes missing data also into account for importing data. 
genfromtxt runs two main loops. The first loop converts each line of the file in a sequence of strings. The second loop converts each string to the appropriate data type. This mechanism is slower than a single loop, but gives more flexibility.

arguments - 

The delimiter keyword is used to define how the splitting should take place. Since we're using csv we use ','

Encoding used to decode the inputfile.  ('unicode-escape')

The presence of a header in the file can hinder data processing.To avoid that we do skip_header=1.



In [2]:
data1 = np.genfromtxt('train.csv', delimiter=',', encoding='unicode_escape', skip_header=0)


In [3]:
tmp_mean = np.nanmean(data1, axis=0)

<ipython-input-3-651f08b10ec9>:1: RuntimeWarning: Mean of empty slice
  tmp_mean = np.nanmean(data1, axis=0)


In [4]:
column_strings = np.argwhere(np.isnan(tmp_mean))

In [5]:
column_numeric = np.argwhere(~np.isnan(tmp_mean)).squeeze()
column_numeric

array([ 0,  1,  3,  4, 17, 18, 19, 20, 26, 34, 36, 37, 38, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       54, 56, 59, 61, 62, 66, 67, 68, 69, 70, 71, 75, 76, 77, 80], dtype=int64)

In [6]:
column_strings=column_strings.squeeze()

In [7]:
da_n = np.genfromtxt('train.csv', delimiter=',', skip_header=False, autostrip=True, encoding='unicode_escape',
                           usecols=column_numeric, dtype=np.str_)

da_n.shape

(1461, 38)

In [8]:
da_n[0]

array(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
       '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='<U13')

In [9]:
header_numeric=da_n[0]
header_numeric

array(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
       '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='<U13')

In [10]:
data = np.genfromtxt('train.csv', delimiter=',', skip_header=False, autostrip=True, encoding='unicode_escape',
                           usecols=column_strings, dtype=np.str_)

data.shape

(1461, 43)

In [11]:
data

array([['MSZoning', 'Street', 'Alley', ..., 'MiscFeature', 'SaleType', 'SaleCondition'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ...,
       ['RL', 'Pave', 'NA', ..., 'Shed', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal']], dtype='<U13')

In [12]:
li=[]

In [13]:
#dropping na more then 50%
for i in range(0,43):
    x=np.unique(data[:, i],return_counts=True)
    for j in range(len(x[0])):
        if(x[0][j]=='NA'):
            index=j
            #print(x[1][index])
            if(x[1][index]>720):
                li.append(i)      

In [14]:
li

[2, 38, 39, 40]

In [15]:
li.reverse()
print(li)

[40, 39, 38, 2]


In [16]:
data.shape

(1461, 43)

In [17]:
data

array([['MSZoning', 'Street', 'Alley', ..., 'MiscFeature', 'SaleType', 'SaleCondition'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ...,
       ['RL', 'Pave', 'NA', ..., 'Shed', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal'],
       ['RL', 'Pave', 'NA', ..., 'NA', 'WD', 'Normal']], dtype='<U13')

In [18]:
for i in li:
    data=np.delete(data,i,1)
    #print('H')

In [19]:
data

array([['MSZoning', 'Street', 'LotShape', ..., 'PavedDrive', 'SaleType', 'SaleCondition'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ...,
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal']], dtype='<U13')

In [20]:
data.shape

(1461, 39)

In [21]:
import numpy as geek 

In [22]:
for i in range(0,len(data[0])):
    x=np.unique(data[:, i],return_counts=True)
    index = np.argmax(x[1], axis=None)
    for j in range(len(data[:, i])):
        data[:, i][j]=geek.char.replace(data[:, i][j], 'NA', x[0][index], count = 1)

In [23]:
data

array([['MSZoning', 'Street', 'LotShape', ..., 'PavedDrive', 'SaleType', 'SaleCondition'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ...,
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal']], dtype='<U13')

In [24]:
temp=data[1:]

In [25]:
temp

array([['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'IR1', ..., 'Y', 'WD', 'Normal'],
       ...,
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD', 'Normal']], dtype='<U13')

In [26]:
for i in range(len(temp[0])):
    keys = np.unique(temp[:,i])
    values = range(1, keys.shape[0]+1)
    dict_col1 = dict(zip(keys,values))
    for g in keys:
        temp[:,i] = np.where(temp[:,i]==g, dict_col1.get(g), temp[:,i])
    

In [27]:
temp

array([['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '1', ..., '3', '9', '5'],
       ...,
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5']], dtype='<U13')

In [28]:
temp = temp.astype(np.int32)
temp

array([[4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 1, ..., 3, 9, 5],
       ...,
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5]])

In [29]:
data

array([['MSZoning', 'Street', 'LotShape', ..., 'PavedDrive', 'SaleType', 'SaleCondition'],
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5'],
       ...,
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5'],
       ['4', '2', '4', ..., '3', '9', '5']], dtype='<U13')

In [30]:
header_strings=data[0]
header_strings

array(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition'], dtype='<U13')

In [31]:
temp

array([[4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 1, ..., 3, 9, 5],
       ...,
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5]])

In [32]:
def checkpoint(filename, checkpoint_header, chekpoint_data):
    np.savez(filename, header=checkpoint_header, data=chekpoint_data)
    checkpoint_variable = np.load(filename+".npz")
    return checkpoint_variable

In [33]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_strings, temp)

In [34]:
checkpoint_strings["data"]

array([[4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 1, ..., 3, 9, 5],
       ...,
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5],
       [4, 2, 4, ..., 3, 9, 5]])

In [35]:
checkpoint_strings["header"]

array(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition'], dtype='<U13')

In [36]:
data_numeric = np.genfromtxt('train.csv', delimiter=',', skip_header=True, autostrip=True, encoding='unicode_escape',
                           usecols=column_numeric)

data_numeric

array([[     1.,     60.,     65., ...,      2.,   2008., 208500.],
       [     2.,     20.,     80., ...,      5.,   2007., 181500.],
       [     3.,     60.,     68., ...,      9.,   2008., 223500.],
       ...,
       [  1458.,     70.,     66., ...,      5.,   2010., 266500.],
       [  1459.,     20.,     68., ...,      4.,   2010., 142125.],
       [  1460.,     20.,     75., ...,      6.,   2008., 147500.]])

In [37]:
x = np.isnan(data_numeric).sum(axis=0)
for n in x:
    print(n, end=', ')

0, 0, 259, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [38]:
tmp_mean=np.nanmean(data_numeric,axis=0)
#col_mean = np.nanmean(a, axis=0)

In [39]:
tmp_mean

array([   730.5    ,     56.89726,     70.04996,  10516.82808,      6.09932,      5.57534,
         1971.26781,   1984.86575,    103.68526,    443.63973,     46.54932,    567.24041,
         1057.42945,   1162.62671,    346.99247,      5.84452,   1515.4637 ,      0.42534,
            0.05753,      1.56507,      0.38288,      2.86644,      1.04658,      6.51781,
            0.61301,   1978.50616,      1.76712,    472.98014,     94.24452,     46.66027,
           21.95411,      3.40959,     15.06096,      2.7589 ,     43.48904,      6.32192,
         2007.81575, 180921.19589])

In [40]:
inds = np.where(np.isnan(data_numeric))

#Place column means in the indices. Align the arrays using take
data_numeric[inds] = np.take(tmp_mean, inds[1])

In [41]:
data_numeric

array([[     1.,     60.,     65., ...,      2.,   2008., 208500.],
       [     2.,     20.,     80., ...,      5.,   2007., 181500.],
       [     3.,     60.,     68., ...,      9.,   2008., 223500.],
       ...,
       [  1458.,     70.,     66., ...,      5.,   2010., 266500.],
       [  1459.,     20.,     68., ...,      4.,   2010., 142125.],
       [  1460.,     20.,     75., ...,      6.,   2008., 147500.]])

In [42]:
x = np.isnan(data_numeric).sum(axis=0)
for n in x:
    print(n, end=', ')

0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [43]:
checkpoint_strings = checkpoint("Checkpoint-numeric", header_numeric, data_numeric)

In [44]:
checkpoint_strings["data"]

array([[     1.,     60.,     65., ...,      2.,   2008., 208500.],
       [     2.,     20.,     80., ...,      5.,   2007., 181500.],
       [     3.,     60.,     68., ...,      9.,   2008., 223500.],
       ...,
       [  1458.,     70.,     66., ...,      5.,   2010., 266500.],
       [  1459.,     20.,     68., ...,      4.,   2010., 142125.],
       [  1460.,     20.,     75., ...,      6.,   2008., 147500.]])

In [45]:
checkpoint_strings["header"]

array(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
       '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='<U13')